version: '2'

services:
  mariadb:
    image: 'mariadb:10.3'
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_drupal
      - MYSQL_PASSWORD=1qaz2wsx
      - MYSQL_DATABASE=bitnami_drupal
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
    ports:
      - '3306:3306'
    volumes:
      - './db_data:/var/lib/mysql'
  drupal:
    image: 'bitnami/drupal:8'
    restart: always
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - DRUPAL_DATABASE_PASSWORD=1qaz2wsx
    ports:
      - '8080:80'
    volumes:
      - './drupal_data:/bitnami'
    depends_on:
      - mariadb
